version: 2

models:
  - name: ods_weather_history
    description: "Таблица с историей наблюдений погоды без дублей"
    config:
      tags: ["ods", "critical"]
    
    tests:
      - elementary.all_columns_anomalies
      - elementary.event_freshness:
          time_bucket:
            period: hour
            count: 1
            timestamp_column: observation_dt
      - elementary.freshness:
          warn_after: {count: 2, period: hour}
          error_after: {count: 4, period: hour}
          timestamp_column: loaded_at
      - elementary.dimension_anomalies:
          dimensions: ["city", "weather_main"]
      - elementary.schema_changes_from_baseline
      - elementary.table_volume_anomalies
          
    columns:
      - name: city
        description: "Название города"
        tests:
          - not_null
          - accepted_values:
              values: ['Kaliningrad']
      - name: temp
        description: "Температура в градусах Цельсия"
        tests:
          - is_realistic_temperature
          - elementary.column_anomalies
      - name: observation_dt
        tests:
          - not_null
      - name: loaded_at
        description: "Время загрузки записи в ODS"
        tests:
          - not_null
      - name: humidity
        tests:
          - elementary.column_anomalies
          - valid_humidity_range
          
  - name: dm_daily_stats
    description: "Ежедневная статистика по городам"
    columns:
      - name: stat_date
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('ods_weather_history')
              field: city