version: 2

models:
  - name: ods_weather_history
    description: "Таблица с историей наблюдений погоды без дублей"
    config:
      tags: ["ods", "critical"]
    
    tests:
      - elementary.all_columns_anomalies
      - elementary.freshness_anomalies:
          timestamp_column: "loaded_at"
          config:
            severity: warn
      - elementary.dimension_anomalies:
          dimensions: ["city", "weather_main"]
      - elementary.schema_changes_from_baseline
      - elementary.event_freshness_anomalies:
          event_timestamp_column: "observation_dt"
          update_timestamp_column: "loaded_at"
          config:
            severity: warn
      - elementary.volume_anomalies:
          where_expression: "city = 'Kaliningrad'"
          time_bucket:
            period: day
            count: 1
          config:
            severity: warn
          
    columns:
      - name: city
        description: "Название города"
        tests:
          - not_null
          - accepted_values:
              values: ['Kaliningrad']
      - name: temp
        description: "Температура в градусах Цельсия"
        tests:
          - is_realistic_temperature
          - elementary.column_anomalies
      - name: observation_dt
        tests:
          - not_null
      - name: loaded_at
        description: "Время загрузки записи в ODS"
        tests:
          - not_null
      - name: humidity
        tests:
          - elementary.column_anomalies
          - valid_humidity_range
          
  - name: dm_daily_stats
    description: "Ежедневная статистика по городам"
    columns:
      - name: stat_date
        tests:
          - unique
          - not_null