FROM apache/airflow:2.7.3-python3.11

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir --user -r /requirements.txt

RUN pip install --no-cache-dir --user \
    dbt-core==1.7.16 \
    dbt-postgres==1.7.16 \
    elementary-data==0.14.1

COPY dags/ /opt/airflow/dags/
RUN mkdir -p /opt/airflow/dbt

USER root
RUN chown -R airflow:root /opt/airflow
USER airflow
