FROM apache/airflow:2.7.3-python3.11

# устанавливаем как root, чтобы пакеты ставились в системный site-packages
USER root

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt && \
    pip install --no-cache-dir \
      dbt-core==1.7.16 \
      dbt-postgres==1.7.16 \
      elementary-data==0.14.1

# Копируем DAGs (если держишь их в образе)
COPY dags/ /opt/airflow/dags/

# Создаем директорию для DBT (при желании монтируешь volume)
RUN mkdir -p /opt/airflow/dbt && chown -R airflow:root /opt/airflow

# Переходим на небезопасного пользователя airflow для запуска
USER airflow
